img_size: 512
base_data_path: /mnt/ncshare/ai4covid_hackathon/
image_base_path: /mnt/ncshare/ai4covid_hackathon/TrainSet
project: ai4covid
weights_base_path: /mnt/ncshare/ai4covid_hackathon/weights/
output_base_path: /mnt/ncshare/ai4covid_hackathon/outputs
train_table_path: /mnt/ncshare/ai4covid_hackathon/trainClinData.xls

corner_ratio: 0.2
center_ratio: 0.1
use_bottom: True

save_images: True