img_size: 512

segmentation_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/segmented
preprocessed_image_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/aligned
brixia_score_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/score_original
fourier_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/fourier_2d
raw_output_base: /mnt/ncshare/ai4covid_hackathon/raw_output

project: ai4covid-xplain

backbone: EfficientNetB0

cnn_encode_dim: 256
transformer_encode_dim: 200
transformer_heads: 15
bahdanau_dim: 256

visualize: True
augment: True

batch_size: 4
epochs: 50
learning_rate: 0.0001
steps_per_epoch: 500
death_rate: 0.25

cross_val_train: True
n_folds: 5
fold: -1

dataset_identifier: age_average

datasets:
  population_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/testClinDataImputedPopAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/validClinDataImputedPopAvg_
    feature_cols: ['Age', 'Sex', 'PositivityAtAdmission', 'Temp_C', 'DaysFever', 'Cough', 'DifficultyInBreathing', 'WBC', 'RBC', 'CRP', 'Fibrinogen', 'Glucose', 'PCT', 'LDH', 'INR', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'PaCO2', 'pH', 'CardiovascularDisease', 'IschemicHeartDisease', 'AtrialFibrillation', 'HeartFailure', 'Ictus', 'HighBloodPressure', 'Diabetes', 'Dementia', 'BPCO', 'Cancer', 'ChronicKidneyDisease', 'RespiratoryFailure', 'Obesity', 'Position']
  population_sampled:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/testClinDataImputedRandSampled.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/validClinDataImputedRandSampled_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
  age_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/testClinDataImputedAgeAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/validClinDataImputedAgeAvg_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
  hospital_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/testClinDataImputedHospAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/validClinDataImputedHospAvg_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
