img_height: 246
img_width: 503

segmentation_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/segmented
preprocessed_image_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/aligned
fourier_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/fourier
brixia_score_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/score_original

train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
test_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_sampled/testClinDataImputedRandSampled.csv

raw_output_base: /mnt/ncshare/ai4covid_hackathon/raw_output

project: ai4covid

n_feature_cols: 41

visualize: True
augment: True

batch_size: 9
epochs: 47
learning_rate: 0.01074
steps_per_epoch: 365
death_rate: .25

cross_val_train: True
n_folds: 5
cv_train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled_
cv_valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_sampled/validClinDataImputedRandSampled_
