img_size: 512

segmentation_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/segmented
preprocessed_image_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/aligned
brixia_score_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/score_original
fourier_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/fourier_2d

train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
test_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/testClinDataImputedPopAvg.csv

raw_output_base: /mnt/ncshare/ai4covid_hackathon/raw_output

project: ai4covid-xplain

cnn_encode_dim: 256
transformer_encode_dim: 200
transformer_heads: 15
bahdanau_dim: 256

feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']

visualize: True
augment: True

batch_size: 4
epochs: 50
learning_rate: 0.0001
steps_per_epoch: 500
death_rate: 0.25

cross_val_train: True
n_folds: 5
cv_train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg_
cv_valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/validClinDataImputedPopAvg_