img_height: 256
img_width: 256
segmentation_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/segmented
preprocessed_image_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/aligned

train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/trainClinDataImputedPopAvg.csv
valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/trainClinDataImputedPopAvg.csv

raw_output_base: /mnt/ncshare/ai4covid_hackathon/raw_output

project: ai4covid

n_feature_cols: 41

visualize: True
augment: True

batch_size: 16
epochs: 20
learning_rate: 0.001
steps_per_epoch: 500

cross_val_train: True
n_folds: 5
cv_train_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg_
cv_valid_table: /home/qbeer/GitHub/ai4covid/data/preprocessed_data/tables/pop_avg/validClinDataImputedPopAvg_