project: ai4covid-image-only

segmentation_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/segmented
preprocessed_image_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/aligned
fourier_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/fourier_2d
brixia_score_base_path: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/train/score_original
raw_output_base: /mnt/ncshare/ai4covid_hackathon/raw_output

img_size: 318
backbone: EfficientNetB0
last_dense_size: 64
batch_size: 9
epochs: 34
learning_rate: 0.01557203541028156
steps_per_epoch: 438
death_rate: 0.26111899568411556
visualize: True
augment: True
cross_val_train: True
fold: -1
n_folds: 5

dataset_identifier: population_average

datasets:
  population_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/testClinDataImputedPopAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/trainClinDataImputedPopAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_avg/validClinDataImputedPopAvg_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
  population_sampled:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/testClinDataImputedRandSampled.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/trainClinDataImputedRandSampled_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/pop_sampled/validClinDataImputedRandSampled_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
  age_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/testClinDataImputedAgeAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/trainClinDataImputedAgeAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/age_avg/validClinDataImputedAgeAvg_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
  hospital_average:
    train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg.csv
    valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg.csv
    test_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/testClinDataImputedHospAvg.csv
    cv_train_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/trainClinDataImputedHospAvg_
    cv_valid_table: /mnt/ncshare/ai4covid_hackathon/preprocessed_data/tables/hosp_avg/validClinDataImputedHospAvg_
    feature_cols: ['Age', 'Sex', 'Temp_C', 'Cough', 'WBC', 'CRP', 'Fibrinogen', 'Glucose', 'LDH', 'D_dimer', 'Ox_percentage', 'PaO2', 'SaO2', 'pH', 'HeartFailure', 'HighBloodPressure', 'Diabetes', 'Cancer', 'RespiratoryFailure', 'Obesity']
